### ISSUE TITLE
`Source0` MUST be an URL.

### ISSUE THREAD

**Issue by pvalena** [fedora-ruby/gem2rpm#100]
Could we possibly add a check for that?
__ _ _

```bash
$ gem2rpm -l -t fedora-27-rawhide -T | grep ^Source0
Source0: <%= download_path %>%{gem_name}-%{version}.gem

$ gem2rpm -l -t fedora-27-rawhide *.gem | grep ^Source0
Source0: %{gem_name}-%{version}.gem

```
_ _ _ _

Version: `rubygem-gem2rpm-1.0.1-1.el7.noarch`

Ref: 
https://github.com/fxn/zeitwerk/blob/2cbb877ec0ab7cb5bfa47208c1ec35d39858abeb/zeitwerk.gemspec

https://bugzilla.redhat.com/show_bug.cgi?id=1755474

**Comment by voxik** [comment]
Could you please elaborate how this happened? I cannot deduce it from your message neither from looking at the code.

**Comment by pvalena** [comment]
Sorry I couln't make it clear the first time:

1. I am using a template (that's shipped with gem2rpm 1.0.1 on `el7`) with ` <%= download_path` included.

2. I use it to create `.spec` file from gem `zeitwerk` in this case. (Not sure what is needed from gem / gemspec on this account.)

3. The created template has `Source0:` without the `download_path`.

___

_ I Hope I did not misunderstood the process of conversion. The URL has to taken from somewhere, so I suppose it should be in gemfile, or is it figured out on runtime? _

**Comment by pvalena** [comment]
I've narrowed the cause- `-l` switch. Also it seems to  happen with all gems and I can reproduce on rawhide too:
```
rubygem-gem2rpm-1.0.1-4.fc31.noarch
```

```
$ gem2rpm -l --fetch gem-compare | grep ^Source
Source0: %{gem_name}-%{version}.gem

$ gem2rpm --fetch gem-compare | grep ^Source
Source0: https://rubygems.org/gems/%{gem_name}-%{version}.gem
```

Is that expected?

**Comment by voxik** [comment]
> I've narrowed the cause- `-l` switch.

The switch was introduced in ad50fce6375b6a7ce1ad1b5d44f685c2b03b3f7e ~15 years ago. Originally, it helped to avoid issues where there is no network connection and this is IMO still its functionality:

~~~
$ bin/gem2rpm gem2rpm-1.0.2.gem | head -n 10
Warning: Could not retrieve full URL for gem2rpm
Warning: Edit the specfile and enter the full download URL as 'Source0' manually
#<Gem2Rpm::DownloadUrlError: SocketError: Failed to open TCP connection to rubygems.org:443 (getaddrinfo: Temporary failure in name resolution) (https://rubygems.org/specs.4.8.gz)>
# Generated from gem2rpm-1.0.2.gem by gem2rpm -*- rpm-spec -*-
%global gem_name gem2rpm

Name: rubygem-%{gem_name}
Version: 1.0.2
Release: 1%{?dist}
Summary: Generate rpm specfiles from gems
License: GPL-2.0+
URL: https://github.com/fedora-ruby/gem2rpm
Source0: %{gem_name}-%{version}.gem
~~~

vs

~~~
$ bin/gem2rpm -l gem2rpm-1.0.2.gem | head -n 10
# Generated from gem2rpm-1.0.2.gem by gem2rpm -*- rpm-spec -*-
%global gem_name gem2rpm

Name: rubygem-%{gem_name}
Version: 1.0.2
Release: 1%{?dist}
Summary: Generate rpm specfiles from gems
License: GPL-2.0+
URL: https://github.com/fedora-ruby/gem2rpm
Source0: %{gem_name}-%{version}.gem
~~~

and with available network:

~~~
$ bin/gem2rpm gem2rpm-1.0.2.gem | head -n 10
# Generated from gem2rpm-1.0.2.gem by gem2rpm -*- rpm-spec -*-
%global gem_name gem2rpm

Name: rubygem-%{gem_name}
Version: 1.0.2
Release: 1%{?dist}
Summary: Generate rpm specfiles from gems
License: GPL-2.0+
URL: https://github.com/fedora-ruby/gem2rpm
Source0: https://rubygems.org/gems/%{gem_name}-%{version}.gem
~~~

vs

~~~
$ bin/gem2rpm -l gem2rpm-1.0.2.gem | head -n 10
# Generated from gem2rpm-1.0.2.gem by gem2rpm -*- rpm-spec -*-
%global gem_name gem2rpm

Name: rubygem-%{gem_name}
Version: 1.0.2
Release: 1%{?dist}
Summary: Generate rpm specfiles from gems
License: GPL-2.0+
URL: https://github.com/fedora-ruby/gem2rpm
Source0: %{gem_name}-%{version}.gem
~~~

While I am not sure what is your use case, I think the behavior is reasonable and I suggest to not use `-l` option.

I also think that it is correct to query RubyGems for the URL, because https://rubygems.org/ might not be the only gem server around.

Based on the above, I am going to reject this request.
