### ISSUE TITLE
SrpmBuilderException: error: line 7: Empty tag: Summary:

### ISSUE THREAD

**Issue by xsuchy** [fedora-ruby/gem2rpm#83]
As seen at:
http://copr-dist-git.fedorainfracloud.org/per-task-logs/320362-f24.log

```
2. Task: 320362-f24, importing the package: None
BUILDER: 3. build via gem2rpm
gem2rpm activeadmin-settings --fetch --srpm
Setting working directory for the following command to: /tmp/tmpw3jACn
gem2rpm activeadmin-settings --fetch --srpm
Exception raised during srpm import:
Traceback (most recent call last):
  File "/usr/share/copr/dist_git/dist_git_importer.py", line 538, in do_import
    provider.get_srpm()
  File "/usr/share/copr/dist_git/dist_git_importer.py", line 164, in get_srpm
    self.provider.get_srpm()
  File "/usr/share/copr/dist_git/dist_git_importer.py", line 394, in get_srpm
    raise SrpmBuilderException(error)
SrpmBuilderException: error: line 7: Empty tag: Summary:

Sending back: 
{"task_id": "320362-f24", "error": "srpm_build_error"}
```

I believe that there is no reason to fail due missing summary (it can be just warning). Just make up something. Even "no summary provided" will work for me.

**Comment by voxik** [comment]
Well, it can't be any placeholder definitely, since we have been there. There used to be default value for license, if non was specified by metadata [1], but there was countless number of .spec files submitted for a Fedora review without properly adjusted license.

So to say, there is already fallback for description, which is using summary if there is some [2]. We might try to do also something similar for summary, but

1. The description is typically longer the it should be.
2. It won't cover 100% of situations, e.g. when there is not summary nor description.

So to say, I am reluctant to implement something like this and I'd suggest to customize just the template you are using for Copr. Something like:

```
Summary: <%= spec.summary.empty? ? "No summary provided" : spec.summary.gsub(/\.$/, "") %>
```

could work for you.

[1] https://github.com/fedora-ruby/gem2rpm/commit/88df2f7f2e67972ea136a8bf060ff02a3ec57909#diff-46f8d17350a7884a20660c975d51570f
[2] https://github.com/fedora-ruby/gem2rpm/blob/master/lib/gem2rpm/specification.rb#L11

**Comment by voxik** [comment]
Sorry, I am going to reject this since:

1. I tried naive implementation using description when summary is missing, but that might result in infinite loop when no description nor summary is provided.
2. Any dummy placeholder might result in more issues then that the gem is not available in Copr.
3. There is really simple workaround in case you really need this.
4. I believe this is rare situation and if this really happens, this should be fixed upstream (in this specific case, once I fix the summary issue, it will fail again with missing license). This is not issue for 99% of the usecases for gem2rpm.
